name: CI

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # - shell: bash
      #   env:
      #     SUPER_SECRET: ${{ secrets.AUTOGREENTOKEN }}
      #     SUPER_SECRET1: ${{ secrets.AUTOGREEN }}
      #   run: |
      #     echo "$SUPER_SECRET"
      #     echo "$SUPER_SECRET1"
          
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.head_ref }}
      #     token: ${{ secrets.AUTOGREENTOKEN }}

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Python Script
        run: |
          python update_cron.py

      - name: Run a one-line script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "liaodoho@gmail.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .github/workflows/ci.yml
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
          git pull --rebase

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
