name: CI

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test action tags by handle'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: "34 15 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # - shell: bash
      #   env:
      #     SUPER_SECRET: ${{ secrets.AUTOGREENTOKEN }}
      #     SUPER_SECRET1: ${{ secrets.AUTOGREEN }}
      #   run: |
      #     echo "$SUPER_SECRET"
      #     echo "$SUPER_SECRET1"
          
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.head_ref }}
      #     token: ${{ secrets.AUTOGREENTOKEN }}

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOGREENTOKEN }}
          ref: ${{ github.head_ref }}
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Python Script
        run: |
          python update_cron.py

      - name: Run a one-line script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.AUTOGREENTOKEN }}
        run: |
          git config --local user.email "liaodoho@gmail.com"
          git config --local user.name "${{ github.actor }}"
          #git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .github/workflows/ci.yml
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
          #git pull --rebase
        # run: |
        # cd clones/org/repo1
        # bash -c 'if [ $(git status --porcelain | wc -l) -eq 0 ]; then
        #   echo "工作树无变更，跳过提交步骤..."
        # else
        #   echo "提交文件中..."
        #   git config user.name "github-actions[bot]"
        #   git config user.email "github-actions[bot]@users.noreply.github.com"
        #   git add .
        #   git commit -m "chore(generated): GitHub Actions Bot 提交的记录"
        #   git log -3 --oneline
        #   echo "推送更新中..."
        #   git push
        # fi'

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
